config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }
  root 'home#index'
  
  resources :stores
  resources :products
  post '/addproduct/:id', to: 'home#add_to_cart', as: 'add_to_cart'
  delete 'deleteproduct/:id', to: 'home#delete_from_cart', as: 'delete_from_cart'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user

  serialize :products, Array

  def cart_total
    total = 0
    products.each do |product|
    total += product.price
  end
  total
end

end

app/models/product.rb
class Product < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_one :cart, dependent: :destroy

  after_create :create_cart

  #class methods
def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
  end
end

 private

 def create_cart
   self.cart = Cart.create
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def add_to_cart
    product = Product.find(params[:id])
    cart = current_user.cart
    cart.products << product
    cart.save
    redirect_to root_path
  end

  def index
    @products = current_user.cart.products
  end

  def delete_from_cart
    cart = current_user.cart
    cart.products.delete_if {|product| product.id.to_s == params[:id]}
    cart.save
    redirect_to root_path
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    #request.env['omniauth.auth'] - all data from handshake
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user
    else
      #something went wrong with registration on Oauth
      #@users.errors - to get any errors that happened
      redirect_to new_user_session_path
    end
  end

#methods to handle each omniauth_callbacks
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
  end

  private

  def set_product
    @product = current_user.products.find(params[:id])
  end
  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  #ended up not using
  def index
  end

  def show
  end

  def edit
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/home/index.html.erb
<h2><%= current_user.email %> </h2>
<hr />

<% if @products.any? %>

<ul class='list-group'>
  <thead><h4>Items:</h4></thead>
    <% @products.each do |product| %>
      <li class='list-group-item'>
         <div class="row">
           <div class="col s3"><%= product.name %></div>
           <div class="s3 offset-s6"><%= link_to 'Delete',
                      delete_from_cart_path(product),
                      class: 'btn btn-danger',
                      data: { confirm: 'Really Delete?'},
                      method: :delete
           %></div>
         </li>
    <% end %>
</ul>

<hr />
<h4> total: <%= number_to_currency current_user.cart.cart_total %> </h4>

<% else %>
<h3>No Products, Go Choose One!</h3>
<% end %>
<%= link_to 'Choose new product', products_path, class: 'btn' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elements</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render(partial: 'shared/navbar') %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h2>Products</h2>

<div class="row">
  <% @products.each do |product| %>
    <div class="col s3">
      <div class="card cyan darken-1">
        <div class="card-content white-text">
          <span class="card-title">
            <%= product.name %> - $<%= product.price %></span>
            <div class="card-action"><%= link_to 'Add to Cart', add_to_cart_path(product), method: :post, data: { confirm: 'Added to cart!' } %></div>
           </div>
         </div>
      </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>Enter New Products</h1>

<div class="row">
   <form class="col s12">
     <div class="row">
       <div class="input-field col s3">
         <input id="product_name" type="text" class="validate">
         <label for="product_name">Product Name</label>
       </div>
       <div class="input-field col s3">
         <input id="product_price" type="text" class="validate">
         <label for="product_price">Product Price</label>
       </div>
       <div class="input-field col s3">
         <input id="product_description" type="text" class="validate">
         <label for="product_description">Product Description</label>
       </div>
       <div class="input-field col s3">
         <input id="product_type" type="text" class="validate">
         <label for="product_type">Product Type</label>
       </div>
     </div>
     <button class="btn waves-effect waves-light" type="submit" name="action">
       <i class="material-icons right"> send</i>
     </button>
   </form>
 </div>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/shared/_navbar.html.erb
<nav>
   <div class="nav-wrapper green darken-1">
     <a href="#" class="brand-logo green darken-1">Elements</a>
     <ul id="nav-mobile" class="right hide-on-med-and-down green darken-1">
       <li><%= link_to 'Products', products_path %></li>
       <li><%= link_to 'Shopping Cart', root_path %></li>
       
       <li>
         <% if user_signed_in? %>
         <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
         <% end %>
       </li>
     </ul>
   </div>
 </nav>

app/views/stores/edit.html.erb
<h1>Stores#edit</h1>
<p>Find me in app/views/stores/edit.html.erb</p>

app/views/stores/index.html.erb
<h1>Stores#index</h1>
<p>Find me in app/views/stores/index.html.erb</p>

app/views/stores/new.html.erb
<h1>Stores#new</h1>
<p>Find me in app/views/stores/new.html.erb</p>

app/views/stores/show.html.erb
<h1>Stores#show</h1>
<p>Find me in app/views/stores/show.html.erb</p>